baseURL = 'https://mparvaneh.ca'
languageCode = 'en-us'
title = 'Matthew Parvaneh'
theme = 'nightfall'

[params]
author = "Matthew Parvaneh"
user = "matt"
hostname = "localhost"

[[params.social]]
key = 0
name = "github"
icon = "fa-brands fa-github"
url = "https://github.com/m-parvaneh"

[[params.social]]
key = 1
name = "resume"
icon = "fa-solid fa-file"
url = "https://www.example.com"

[[params.social]]
key = 2
name = "linkedin"
icon = "fa-brands fa-linkedin"
url = "https://www.linkedin.com/in/matthewparvaneh/"

[[params.social]]
key = 3
name = "email"
icon = "fa-solid fa-envelope"
url = "mailto:mattparvaneh@outlook.com"
